// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmmbllsoumvwrxvxgovb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtbWJsbHNvdW12d3J4dnhnb3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODQ4NDQsImV4cCI6MjA3MDM2MDg0NH0.pHBn42mNsH3mc7wV_hokQci2DOLfMK4ZAda9MiRQ610";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});